[package]
name = "wgpu_automata"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.18.0", features = ["derive"] }
env_logger = "0.11.5"
log = "0.4.22"
pollster = "0.3.0"
rand = "0.8.5"
wgpu = "22.1.0"
winit = { version = "0.30.5", features = ["rwh_05"] }
