[package]
name = "a01_hello_triangle"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
pollster = "0.3.0"
wgpu = { version = "22.1.0", features = ["metal"] }
winit = { version = "0.30.5", features = ["android-native-activity"] }
