[package]
name = "b01_wgpu_test_winit0_30"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
log = "0.4.22"
pollster = "0.3.0"
wgpu = "22.1.0"
winit = { version = "0.30.5", features = ["rwh_05"] }
